CREATE TABLE Employees
(
	Id INT IDENTITY(1,1),
	FullName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50),
	Gender INT NOT NULL,
	DateOfJoining DATETIME,
	Salary DECIMAL,
	PRIMARY KEY(Id),
	CONSTRAINT EmployeesUniqueEmail UNIQUE(Email)
)