CREATE TABLE Employees(

Id INT IDENTITY(1,1),
FullName NVARCHAR(50) NOT NULL,
Email NVARCHAR(50),
Gender INT NOT NULL,
JoinDate DATETIME,
Salary DECIMAL,

PRIMARY KEY(Id),
CONSTRAINT UC_Employees UNIQUE(Email)
)