CREATE TABLE Employees
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FullName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50),
	Gender INT NOT NULL,
	DateOfJoining DATETIME,
	Salary DECIMAL,
	CONSTRAINT UQ_Employees_Email UNIQUE(Email)
)